In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt 
import matplotlib
%matplotlib inline 


In [2]:
os.chdir("C:\JUPITER\SHAD BASE\DL 1")

In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

Using TensorFlow backend.


In [4]:
df=pd.read_csv('Wine.txt', sep='\t', header=0)

In [5]:
df.head(150)

Input1  Input2  Input3  Input4  Input5  Input6  Input7  Input8  Input9  \
0     14.23    1.71    2.43    15.6     127    2.80    3.06    0.28    2.29   
1     13.20    1.78    2.14    11.2     100    2.65    2.76    0.26    1.28   
2     13.16    2.36    2.67    18.6     101    2.80    3.24    0.30    2.81   
3     14.37    1.95    2.50    16.8     113    3.85    3.49    0.24    2.18   
4     13.24    2.59    2.87    21.0     118    2.80    2.69    0.39    1.82   
5     14.20    1.76    2.45    15.2     112    3.27    3.39    0.34    1.97   
6     14.39    1.87    2.45    14.6      96    2.50    2.52    0.30    1.98   
7     14.06    2.15    2.61    17.6     121    2.60    2.51    0.31    1.25   
8     14.83    1.64    2.17    14.0      97    2.80    2.98    0.29    1.98   
9     13.86    1.35    2.27    16.0      98    2.98    3.15    0.22    1.85   
10    14.10    2.16    2.30    18.0     105    2.95    3.32    0.22    2.38   
11    14.12    1.48    2.32    16.8      95    2.20    2.43    0.26    1.57   
12    13.75    1.73    2.41    16.0      89    2.60    2.76    0.29    1.81   
13    14.75    1.73    2.39    11.4      91    3.10    3.69    0.43    2.81   
14    14.38    1.87    2.38    12.0     102    3.30    3.64    0.29    2.96   
15    13.63    1.81    2.70    17.2     112    2.85    2.91    0.30    1.46   
16    14.30    1.92    2.72    20.0     120    2.80    3.14    0.33    1.97   
17    13.83    1.57    2.62    20.0     115    2.95    3.40    0.40    1.72   
18    14.19    1.59    2.48    16.5     108    3.30    3.93    0.32    1.86   
19    13.64    3.10    2.56    15.2     116    2.70    3.03    0.17    1.66   
20    14.06    1.63    2.28    16.0     126    3.00    3.17    0.24    2.10   
21    12.93    3.80    2.65    18.6     102    2.41    2.41    0.25    1.98   
22    13.71    1.86    2.36    16.6     101    2.61    2.88    0.27    1.69   
23    12.85    1.60    2.52    17.8      95    2.48    2.37    0.26    1.46   
24    13.50    1.81    2.61    20.0      96    2.53    2.61    0.28    1.66   
25    13.05    2.05    3.22    25.0     124    2.63    2.68    0.47    1.92   
26    13.39    1.77    2.62    16.1      93    2.85    2.94    0.34    1.45   
27    13.30    1.72    2.14    17.0      94    2.40    2.19    0.27    1.35   
28    13.87    1.90    2.80    19.4     107    2.95    2.97    0.37    1.76   
29    14.02    1.68    2.21    16.0      96    2.65    2.33    0.26    1.98   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
120   11.45    2.40    2.42    20.0      96    2.90    2.79    0.32    1.83   
121   11.56    2.05    3.23    28.5     119    3.18    5.08    0.47    1.87   
122   12.42    4.43    2.73    26.5     102    2.20    2.13    0.43    1.71   
123   13.05    5.80    2.13    21.5      86    2.62    2.65    0.30    2.01   
124   11.87    4.31    2.39    21.0      82    2.86    3.03    0.21    2.91   
125   12.07    2.16    2.17    21.0      85    2.60    2.65    0.37    1.35   
126   12.43    1.53    2.29    21.5      86    2.74    3.15    0.39    1.77   
127   11.79    2.13    2.78    28.5      92    2.13    2.24    0.58    1.76   
128   12.37    1.63    2.30    24.5      88    2.22    2.45    0.40    1.90   
129   12.04    4.30    2.38    22.0      80    2.10    1.75    0.42    1.35   
130   12.86    1.35    2.32    18.0     122    1.51    1.25    0.21    0.94   
131   12.88    2.99    2.40    20.0     104    1.30    1.22    0.24    0.83   
132   12.81    2.31    2.40    24.0      98    1.15    1.09    0.27    0.83   
133   12.70    3.55    2.36    21.5     106    1.70    1.20    0.17    0.84   
134   12.51    1.24    2.25    17.5      85    2.00    0.58    0.60    1.25   
135   12.60    2.46    2.20    18.5      94    1.62    0.66    0.63    0.94   
136   12.25    4.72    2.54    21.0      89    1.38    0.47    0.53    0.80   
137   12.53    5.51    2.64    25.0      96    1.79    0.60    0.63    1.10   
138   13.49    3.59    2.19    19.5      88    1.62    

In [6]:
df['Desired1(3)'].value_counts(normalize=True)

2    0.398876
0    0.331461
1    0.269663
Name: Desired1(3), dtype: float64

In [7]:
Y=df['Desired1(3)']
X=df.drop('Desired1(3)', axis=1)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=12345,
                                                    # доля объёма тестового множества
                                                    test_size=0.33)

In [9]:
X_train = X_train.values
X_test = X_test.values
Y_train = Y_train.values
Y_test = Y_test.values


In [10]:
Y_train_bin = np_utils.to_categorical(Y_train)

Y_test_bin = np_utils.to_categorical(Y_test)

In [11]:
Y_train_bin[0:5]

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [12]:
# Creating a model
model = Sequential()
model.add(Dense(9, input_dim=13, activation='relu'))
model.add(Dense(10, activation='relu', ))
model.add(Dense(3, activation='softmax'))


# Compiling model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


# Training a model
model.fit(X_train, Y_train_bin, epochs=300, batch_size=10)


Epoch 1/300
119/119 [==============================] - 0s 496us/step - loss: 1.3590 - accuracy: 0.3866
Epoch 2/300
119/119 [==============================] - 0s 76us/step - loss: 1.0999 - accuracy: 0.2689
Epoch 3/300
119/119 [==============================] - 0s 67us/step - loss: 1.1000 - accuracy: 0.3193
Epoch 4/300
119/119 [==============================] - 0s 76us/step - loss: 1.0994 - accuracy: 0.3193
Epoch 5/300
119/119 [==============================] - 0s 67us/step - loss: 1.0986 - accuracy: 0.3193
Epoch 6/300
119/119 [==============================] - 0s 67us/step - loss: 1.0981 - accuracy: 0.3697
Epoch 7/300
119/119 [==============================] - 0s 67us/step - loss: 1.0974 - accuracy: 0.4118
Epoch 8/300
119/119 [==============================] - 0s 67us/step - loss: 1.0966 - accuracy: 0.4118
Epoch 9/300
119/119 [==============================] - 0s 67us/step - loss: 1.0959 - accuracy: 0.4118
Epoch 10/300
119/119 [==============================] - 0s 67us/step - loss: 1.09

In [13]:
# evaluate the model
scores = model.evaluate(X_test, Y_test_bin)
print("\nAccuracy: %.2f%%" % (scores[1]*100))

59/59 [==============================] - 0s 203us/step

Accuracy: 37.29%


In [14]:
# calculate predictions
predictions = model.predict(X_test)
# round predictions
# rounded = [round(x[0]) for x in predictions]
# print(rounded)

In [15]:
print(predictions[0:5])

[[0.3194572  0.26888973 0.41165313]
 [0.3194572  0.26888973 0.41165313]
 [0.3194572  0.26888973 0.41165313]
 [0.3194572  0.26888973 0.41165313]
 [0.3194572  0.26888973 0.41165313]]


In [16]:
from keras import optimizers
from keras import initializers

In [21]:
init_2 = initializers.TruncatedNormal(mean=0.0, stddev=0.05, seed=12345)
init_3 = initializers.Constant(value = 1e-3)

model3 = Sequential()
model3.add(Dense(9, input_dim=13, activation='relu', kernel_initializer=init_2, bias_initializer=init_3))
model3.add(Dense(10, activation='relu', kernel_initializer=init_2, bias_initializer=init_3 ))
model3.add(Dense(3, activation='softmax', kernel_initializer=init_2, bias_initializer=init_3))


#  kernel_initializer='random_uniform', bias_initializer='zeros'))


# Compiling model

sgd2 = optimizers.SGD(lr=0.02, decay=1e-6, momentum=0.8, nesterov=True)
model3.compile(loss='categorical_crossentropy', optimizer=sgd2, metrics=['accuracy'])

#  model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


# Training a model
model3.fit(X_train, Y_train_bin, epochs=300, batch_size=10)


Epoch 1/300
119/119 [==============================] - 0s 262us/step - loss: 1.2225 - accuracy: 0.3950
Epoch 2/300
119/119 [==============================] - 0s 131us/step - loss: 1.0911 - accuracy: 0.4118
Epoch 3/300
119/119 [==============================] - 0s 0us/step - loss: 1.0879 - accuracy: 0.4118
Epoch 4/300
119/119 [==============================] - 0s 67us/step - loss: 1.0867 - accuracy: 0.4118
Epoch 5/300
119/119 [==============================] - 0s 59us/step - loss: 1.0860 - accuracy: 0.4118
Epoch 6/300
119/119 [==============================] - 0s 59us/step - loss: 1.0848 - accuracy: 0.4118
Epoch 7/300
119/119 [==============================] - 0s 67us/step - loss: 1.0853 - accuracy: 0.4118
Epoch 8/300
119/119 [==============================] - 0s 59us/step - loss: 1.0858 - accuracy: 0.4118
Epoch 9/300
119/119 [==============================] - 0s 59us/step - loss: 1.0857 - accuracy: 0.4118
Epoch 10/300
119/119 [==============================] - 0s 67us/step - loss: 1.08

In [22]:
# evaluate the model
scores = model3.evaluate(X_test, Y_test_bin)
print("\nAccuracy: %.2f%%" % (scores[1]*100))

59/59 [==============================] - 0s 220us/step

Accuracy: 37.29%


In [23]:
# calculate predictions
predictions_3 = model3.predict(X_test)
# round predictions
# rounded = [round(x[0]) for x in predictions]
# print(rounded)

In [24]:
print(predictions_3[0:5])

[[0.32018209 0.26866364 0.41115433]
 [0.32018209 0.26866364 0.41115433]
 [0.32018209 0.26866364 0.41115433]
 [0.32018209 0.26866364 0.41115433]
 [0.32018209 0.26866364 0.41115433]]
